version: '3.7'

services:
  monitoring-prometheus:
    image: prom/prometheus:latest
    hostname: monitoring-prometheus
    container_name: monitoring-prometheus
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: ./prometheus/prometheus/config/prometheus.yml
        target: /etc/prometheus/prometheus.yml
        read_only: true
      - type: bind
        source: ./prometheus/data/prometheus
        target: /prometheus
    networks:
      - monitoring-network

  monitoring-alertmanager:
    image: prom/alertmanager:latest
    hostname: monitoring-alertmanager
    container_name: monitoring-alertmanager
    ports:
      - "9093:9093"
    volumes:
      - type: bind
        source: ./prometheus/alertmanager/config/alertmanager.yml
        target: /etc/alertmanager/alertmanager.yml
        read_only: true
      - type: bind
        source: ./prometheus/data/alertmanager
        target: /alertmanager
    networks:
      - monitoring-network

  monitoring-grafana:
    image: grafana/grafana:latest
    hostname: monitoring-grafana
    container_name: monitoring-grafana
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./prometheus/data/grafana
        target: /var/lib/grafana
      - type: bind
        source: ./prometheus/grafana/config/grafana.ini
        target: /etc/grafana/grafana.ini
      - type: bind
        source: ./prometheus/grafana/dashboards
        target: /etc/grafana/provisioning/dashboards
      - type: bind
        source: ./prometheus/grafana/datasources
        target: /etc/grafana/provisioning/datasources
    networks:
      - monitoring-network
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    hostname: node-exporter
    restart: always
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=123456
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    networks:
      - monitoring-network

  influxdb:
    image: influxdb:alpine
    container_name: influxdb
    volumes:
      - ./prometheus/influxdb/data:/var/lib/influxdb/data
    ports:
      - "8083:8083"
      - "8086:8086"
    networks:
      - monitoring-network

networks:
  monitoring-network:
    driver: bridge
