version: '3'

# 网桥mongo -> 方便相互通讯
networks:
  mongo:

services:
  mongo:
    image: mongo:4.4.6
    container_name: mongo
    hostname: mongo
    restart: unless-stopped
    networks:
      - mongo
    ports:
      - "27017:27017"
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - /etc/localtime:/etc/localtime
      - ./mongodb/db:/data/db
      - ./mongodb/log:/data/log
      - ./mongodb/conf:/data/configdb
      - ./mongodb/init/:/docker-entrypoint-initdb.d/
    command: mongod
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    links:
      - mongo:mongo
    depends_on:
      - mongo
    networks:
      - mongo
    ports:
      - "27018:8081"
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: 3024-night
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: 123456
      
  # 可视化图形工具
  adminmongo:
    image: mrvautin/adminmongo
    restart: unless-stopped
    container_name: adminmongo
    environment:
      - HOST=0.0.0.0
    depends_on:
      - mongo
    links:
      - mongo:mongo
    ports:
      - "1234:1234"
    networks:
      - mongo
