# 参考文档： https://www.xuxueli.com/xxl-job
# admin 123456
# 导入MySQL脚本
version: "3"
services:
  mysql:
    image: mysql:5.7.38
    container_name: mysql
    restart: unless-stopped
    environment:
      # 指定root密码。不指定则会启动失败
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=xxl_job
      - TZ=Asia/Shanghai
    volumes:
      # db文件存放地址
      - ./xxljbo/mysql/data:/var/lib/mysql
      - ./xxljbo/mysql/log:/var/log/mysql         # log
    command:
      # --lower_case_table_names 表名统一不区分大小写
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    ports:
      - 3306:3306
      
      
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.3.1 # 原镜像`xuxueli/xxl-job-admin:2.3.0`
    container_name: xxl-job-admin
    environment:
      # TODO 根据自己的配置修改，配置项参考源码文件：/xxl-job/xxl-job-admin/src/main/resources/application.properties
      PARAMS: "--spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
               --spring.datasource.username=root
               --spring.datasource.password=123456
               --server.servlet.context-path=/xxl-job-admin
               --spring.mail.host=smtp.qq.com
               --spring.mail.port=25
               --spring.mail.username=xxx@qq.com
               --spring.mail.from=xxx@qq.com
               --spring.mail.password=xxx
               --xxl.job.accessToken="
    ports:
      - "8080:8080"
    volumes:
      - ./xxljbo/xxljbo/tapplogs:/data/applogs
    depends_on:
      - mysql
