# 可参考： https://github.com/openzipkin/zipkin/blob/master/docker/examples/docker-compose-mysql.yml
version: '3'

networks:
  zipkin:
    driver: bridge

services:
  zipkin:
    image: openzipkin/zipkin:latest  # 原镜像`openzipkin/zipkin:2`
    container_name: zipkin           # 容器名为'zipkin'
    restart: unless-stopped          # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    environment:                        # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      # 基于mysql存储
      STORAGE_TYPE: mysql
      # Point the zipkin at the storage backend
      # TODO 修改数据库配置信息
      MYSQL_HOST: mysql
      MYSQL_TCP_PORT: 3306
      MYSQL_DB: zipkin
      MYSQL_USER: root
      MYSQL_PASS: 123456
        # Uncomment to enable scribe
        #   SCRIBE_ENABLED: true
        # Uncomment to enable self-tracing
        #   SELF_TRACING_ENABLED: true
        # Uncomment to enable debug logging
        #   JAVA_OPTS: -Dlogging.level.zipkin=DEBUG -Dlogging.level.zipkin2=DEBUG
    ports:                              # 映射端口
      - "9411:9411"
    depends_on:
      - mysql
    networks:
      - zipkin
      
  mysql:
    image: mysql:5.7  # 原镜像`mysql:5.7`
    container_name: mysql       # 容器名为'mysql'
    restart: unless-stopped          # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    volumes:                         # 数据卷挂载路径设置,将本机目录映射到容器目录
      #- "./yearning/mysql/my.cnf:/etc/mysql/my.cnf"
      - "./zipkin/mysql/data:/var/lib/mysql"
      - "./zipkin/mysql/conf.d:/etc/mysql/conf.d"
      # - /data/docker/var/run/mysql-3306.sock:/var/run/mysql.sock
    environment:                        # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MYSQL_ROOT_PASSWORD: 123456         # 设置root用户密码
      MYSQL_DATABASE: zipkin          # 初始化的数据库名称
      
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:                              # 映射端口
      - "3306:3306"
    networks:
      - zipkin
