# https://hub.docker.com/_/sonarqube
# https://github.com/SonarSource/docker-sonarqube
# https://github.com/xuhuisheng/sonar-l10n-zh
# http://[host]:9000  admin/admin
version: '3'

# 网桥elk -> 方便相互通讯
networks:
  sonarqube:

services:
  # postgres
  postgres:
    image: postgres:12.3
    restart: unless-stopped
    container_name: sonarqube_postgres
    ports:
      - "54320:5432"
    volumes:
      - "./sonarqube/postgres/postgresql:/var/lib/postgresql"
      - "./sonarqube/postgres/data:/var/lib/postgresql/data"
      - "/etc/localtime:/etc/localtime:ro"  # 设置与宿主机时间同步
    environment:
      TZ: Asia/Shanghai
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    networks:
      - sonarqube

  # sonarqube
  sonarqube:
    image: sonarqube:9.5.0-community      # 原镜像`sonarqube:9.5.0-community`
    container_name: sonarqube
    restart: unless-stopped        # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    privileged: true
    volumes:
      - "./sonarqube/data:/opt/sonarqube/data"
      - "./sonarqube/logs:/opt/sonarqube/logs"
      - "./sonarqube/extensions:/opt/sonarqube/extensions"
      - "./sonarqube/temp:/opt/sonarqube/temp"
      - "/etc/localtime:/etc/localtime:ro"  # 设置与宿主机时间同步
    command:
      # 内存设置
      - -Dsonar.ce.javaOpts=-Xmx1024m
      - -Dsonar.web.javaOpts=-Xmx1024m
      # 设置服务代理路径
      - -Dsonar.web.context=/
      # 此设置用于集成gitlab时，回调地址设置
      - -Dsonar.core.serverBaseURL=https://sonarqube.example.com
    environment:
      TZ: Asia/Shanghai
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
      SONARQUBE_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    networks:
      - sonarqube
      
